### ISSUE TITLE
Unexpected token 

### ISSUE THREAD

**Issue by jimmywarting** [pocesar/js-diacritic-regex#2]
I'm getting this warning message and can't figure out what causing it
```
WARNING in ./~/diacritic-regex/index.d.ts
Module parse failed: my_project/node_modules/diacritic-regex/index.d.ts Unexpected token (1:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:7)
    at Parser.pp$4.raise (my_project/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (my_project/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.expect (my_project/node_modules/acorn/dist/acorn.js:597:28)
    at Parser.pp$1.parseExportSpecifiers (my_project/node_modules/acorn/dist/acorn.js:1215:10)
    at Parser.pp$1.parseExport (my_project/node_modules/acorn/dist/acorn.js:1186:30)
    at Parser.pp$1.parseStatement (my_project/node_modules/acorn/dist/acorn.js:719:71)
    at Parser.pp$1.parseTopLevel (my_project/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (my_project/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (my_project/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (my_project/node_modules/webpack/lib/Parser.js:902:15)
 @ ./~/diacritic-regex ^\.\/.*$
```

**Comment by pocesar** [comment]
your webpack configuration is trying to load the typings files
